// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.1
// source: proto/grpcmetric.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JSONSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JSONMetrics   []byte                 `protobuf:"bytes,1,opt,name=JSONMetrics,proto3" json:"JSONMetrics,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONSaveRequest) Reset() {
	*x = JSONSaveRequest{}
	mi := &file_proto_grpcmetric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONSaveRequest) ProtoMessage() {}

func (x *JSONSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcmetric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONSaveRequest.ProtoReflect.Descriptor instead.
func (*JSONSaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcmetric_proto_rawDescGZIP(), []int{0}
}

func (x *JSONSaveRequest) GetJSONMetrics() []byte {
	if x != nil {
		return x.JSONMetrics
	}
	return nil
}

func (x *JSONSaveRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type JSONSaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONSaveResponse) Reset() {
	*x = JSONSaveResponse{}
	mi := &file_proto_grpcmetric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONSaveResponse) ProtoMessage() {}

func (x *JSONSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcmetric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONSaveResponse.ProtoReflect.Descriptor instead.
func (*JSONSaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcmetric_proto_rawDescGZIP(), []int{1}
}

func (x *JSONSaveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JSONSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_grpcmetric_proto protoreflect.FileDescriptor

var file_proto_grpcmetric_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x22, 0x47, 0x0a, 0x0f, 0x4a, 0x53, 0x4f, 0x4e, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4a, 0x53, 0x4f, 0x4e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x4a, 0x53,
	0x4f, 0x4e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x42, 0x0a,
	0x10, 0x4a, 0x53, 0x4f, 0x4e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x57, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x4c, 0x0a, 0x0f,
	0x53, 0x61, 0x76, 0x65, 0x4a, 0x53, 0x4f, 0x4e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12,
	0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x4a, 0x53, 0x4f,
	0x4e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x63, 0x75, 0x6d, 0x2d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_grpcmetric_proto_rawDescOnce sync.Once
	file_proto_grpcmetric_proto_rawDescData = file_proto_grpcmetric_proto_rawDesc
)

func file_proto_grpcmetric_proto_rawDescGZIP() []byte {
	file_proto_grpcmetric_proto_rawDescOnce.Do(func() {
		file_proto_grpcmetric_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_grpcmetric_proto_rawDescData)
	})
	return file_proto_grpcmetric_proto_rawDescData
}

var file_proto_grpcmetric_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grpcmetric_proto_goTypes = []any{
	(*JSONSaveRequest)(nil),  // 0: grpcmetric.JSONSaveRequest
	(*JSONSaveResponse)(nil), // 1: grpcmetric.JSONSaveResponse
}
var file_proto_grpcmetric_proto_depIdxs = []int32{
	0, // 0: grpcmetric.Metrics.SaveJSONMetrics:input_type -> grpcmetric.JSONSaveRequest
	1, // 1: grpcmetric.Metrics.SaveJSONMetrics:output_type -> grpcmetric.JSONSaveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grpcmetric_proto_init() }
func file_proto_grpcmetric_proto_init() {
	if File_proto_grpcmetric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_grpcmetric_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcmetric_proto_goTypes,
		DependencyIndexes: file_proto_grpcmetric_proto_depIdxs,
		MessageInfos:      file_proto_grpcmetric_proto_msgTypes,
	}.Build()
	File_proto_grpcmetric_proto = out.File
	file_proto_grpcmetric_proto_rawDesc = nil
	file_proto_grpcmetric_proto_goTypes = nil
	file_proto_grpcmetric_proto_depIdxs = nil
}
